/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lms_V1.pkg2.pkg0.view;

import java.awt.Color;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import lms_V1.pkg2.pkg0.domain.LibrarianAccount;
import lms_V1.pkg2.pkg0.service.LibrarianService;

/**
 *
 * @author anik
 */
public class CreateLibrarianAccount extends javax.swing.JFrame {

    private LibrarianAccount librarianAccount;
    private LibrarianService librarianService;
    private int librarianID=0;
    
    
    /**
     * Creates new form CreateLibrarianAccount
     */
    public CreateLibrarianAccount() {
        this.setTitle("Create Librarian Account ( LMS )");
        initComponents();
        displayLibrarianInformationWithInTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        librarianScrolBar = new javax.swing.JScrollBar();
        jpanCreateAdminAccount = new javax.swing.JPanel();
        scPanCreateAdminAccount = new javax.swing.JScrollPane();
        subPanCreateAdminAccount = new javax.swing.JPanel();
        jLabel84 = new javax.swing.JLabel();
        jPanel33 = new javax.swing.JPanel();
        txtLibrarianHouseNo = new javax.swing.JTextField();
        txtLibrarianMobileNo = new javax.swing.JTextField();
        jLabel70 = new javax.swing.JLabel();
        txtLibrarianBlockOrvVillage = new javax.swing.JTextField();
        txtLibrarianEmail = new javax.swing.JTextField();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        txtLibrarianRoadNo = new javax.swing.JTextField();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        txtLibrarianCardNo = new javax.swing.JTextField();
        txtLibrarianThana = new javax.swing.JTextField();
        jLabel79 = new javax.swing.JLabel();
        txtLibrarianName = new javax.swing.JTextField();
        lblShowMsgInLibrarianAccountPan = new javax.swing.JLabel();
        comboLibrarianDistrict = new javax.swing.JComboBox<>();
        comboLibrarianDivision = new javax.swing.JComboBox<>();
        jLabel106 = new javax.swing.JLabel();
        radioBtnShiftMorning = new javax.swing.JRadioButton();
        radioBtnShiftDay = new javax.swing.JRadioButton();
        jLabel107 = new javax.swing.JLabel();
        txtLibrarianUserName = new javax.swing.JTextField();
        jLabel108 = new javax.swing.JLabel();
        txtLibrarianPassword = new javax.swing.JTextField();
        jLabel110 = new javax.swing.JLabel();
        txtLibrarianConfirmPassword = new javax.swing.JTextField();
        btnAddLibrarianRecord = new javax.swing.JButton();
        jLabel111 = new javax.swing.JLabel();
        jLabel114 = new javax.swing.JLabel();
        jPanel34 = new javax.swing.JPanel();
        jScrollPane25 = new javax.swing.JScrollPane();
        tblDisplayLibrarianAccount = new javax.swing.JTable();
        jPanel37 = new javax.swing.JPanel();
        btnDeleteLibrarianAccount = new javax.swing.JButton();
        txtLibrarianAccountSearchBar = new javax.swing.JTextField();
        btnSearchLibrarianAccount = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel80 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        jLabel95 = new javax.swing.JLabel();
        lblShowLibrarianName = new javax.swing.JLabel();
        lblShowLibrarianCodeNo = new javax.swing.JLabel();
        lblShowLibrarianMobileNumber = new javax.swing.JLabel();
        jLabel109 = new javax.swing.JLabel();
        lblShowLibrarianEmail = new javax.swing.JLabel();
        lblShowLibrarianAddress = new javax.swing.JLabel();
        lblShowDelLibrarianAccountPan = new javax.swing.JLabel();
        jLabel113 = new javax.swing.JLabel();
        btnClearDelLibrarianAccountPan = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel112 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();

        librarianScrolBar.setUnitIncrement(50);
        librarianScrolBar.setValueIsAdjusting(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jpanCreateAdminAccount.setBackground(new java.awt.Color(255, 51, 204));
        jpanCreateAdminAccount.setPreferredSize(new java.awt.Dimension(996, 678));

        scPanCreateAdminAccount.setBorder(null);
        scPanCreateAdminAccount.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        scPanCreateAdminAccount.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        scPanCreateAdminAccount.setPreferredSize(new java.awt.Dimension(996, 678));
        scPanCreateAdminAccount.setVerticalScrollBar(librarianScrolBar);

        subPanCreateAdminAccount.setBackground(new java.awt.Color(255, 255, 255));
        subPanCreateAdminAccount.setPreferredSize(new java.awt.Dimension(1280, 1700));

        jLabel84.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        jLabel84.setForeground(new java.awt.Color(51, 51, 51));
        jLabel84.setText("|  Create Librarian Account");

        jPanel33.setBackground(new java.awt.Color(255, 255, 255));
        jPanel33.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(153, 153, 153))); // NOI18N

        txtLibrarianHouseNo.setFont(new java.awt.Font("SimSun", 0, 14)); // NOI18N
        txtLibrarianHouseNo.setForeground(new java.awt.Color(102, 102, 102));

        txtLibrarianMobileNo.setFont(new java.awt.Font("SimSun", 0, 14)); // NOI18N
        txtLibrarianMobileNo.setForeground(new java.awt.Color(102, 102, 102));

        jLabel70.setFont(new java.awt.Font("SimSun", 0, 15)); // NOI18N
        jLabel70.setForeground(new java.awt.Color(102, 102, 102));
        jLabel70.setText("Librarian Card:");

        txtLibrarianBlockOrvVillage.setFont(new java.awt.Font("SimSun", 0, 14)); // NOI18N
        txtLibrarianBlockOrvVillage.setForeground(new java.awt.Color(102, 102, 102));

        txtLibrarianEmail.setFont(new java.awt.Font("SimSun", 0, 14)); // NOI18N
        txtLibrarianEmail.setForeground(new java.awt.Color(102, 102, 102));

        jLabel71.setFont(new java.awt.Font("SimSun", 0, 15)); // NOI18N
        jLabel71.setForeground(new java.awt.Color(102, 102, 102));
        jLabel71.setText("Road NO:");

        jLabel72.setFont(new java.awt.Font("SimSun", 0, 15)); // NOI18N
        jLabel72.setForeground(new java.awt.Color(102, 102, 102));
        jLabel72.setText("District:");

        txtLibrarianRoadNo.setFont(new java.awt.Font("SimSun", 0, 14)); // NOI18N
        txtLibrarianRoadNo.setForeground(new java.awt.Color(102, 102, 102));

        jLabel73.setFont(new java.awt.Font("SimSun", 0, 15)); // NOI18N
        jLabel73.setForeground(new java.awt.Color(102, 102, 102));
        jLabel73.setText("Block/Village:");

        jLabel74.setFont(new java.awt.Font("SimSun", 0, 15)); // NOI18N
        jLabel74.setForeground(new java.awt.Color(102, 102, 102));
        jLabel74.setText("Mobile No:");

        jLabel75.setFont(new java.awt.Font("SimSun", 0, 15)); // NOI18N
        jLabel75.setForeground(new java.awt.Color(102, 102, 102));
        jLabel75.setText("Division:");

        jLabel76.setFont(new java.awt.Font("SimSun", 0, 15)); // NOI18N
        jLabel76.setForeground(new java.awt.Color(102, 102, 102));
        jLabel76.setText("Librarian Name:");

        jLabel77.setFont(new java.awt.Font("SimSun", 0, 15)); // NOI18N
        jLabel77.setForeground(new java.awt.Color(102, 102, 102));
        jLabel77.setText("Email:");

        jLabel78.setFont(new java.awt.Font("SimSun", 0, 15)); // NOI18N
        jLabel78.setForeground(new java.awt.Color(102, 102, 102));
        jLabel78.setText("House No:");

        txtLibrarianCardNo.setFont(new java.awt.Font("SimSun", 0, 14)); // NOI18N
        txtLibrarianCardNo.setForeground(new java.awt.Color(102, 102, 102));

        txtLibrarianThana.setFont(new java.awt.Font("SimSun", 0, 14)); // NOI18N
        txtLibrarianThana.setForeground(new java.awt.Color(102, 102, 102));

        jLabel79.setFont(new java.awt.Font("SimSun", 0, 15)); // NOI18N
        jLabel79.setForeground(new java.awt.Color(102, 102, 102));
        jLabel79.setText("Thana:");

        txtLibrarianName.setFont(new java.awt.Font("SimSun", 0, 14)); // NOI18N
        txtLibrarianName.setForeground(new java.awt.Color(102, 102, 102));

        lblShowMsgInLibrarianAccountPan.setFont(new java.awt.Font("SimSun", 0, 14)); // NOI18N
        lblShowMsgInLibrarianAccountPan.setForeground(new java.awt.Color(255, 0, 255));
        lblShowMsgInLibrarianAccountPan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblShowMsgInLibrarianAccountPan.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2), "[ Message ]", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("SimSun", 0, 14), new java.awt.Color(153, 153, 153))); // NOI18N

        comboLibrarianDistrict.setEditable(true);
        comboLibrarianDistrict.setFont(new java.awt.Font("SimSun", 0, 14)); // NOI18N
        comboLibrarianDistrict.setForeground(new java.awt.Color(102, 102, 102));
        comboLibrarianDistrict.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select District", "Dhaka", "Norshingdi", "Feni", "comilla", "Nogaon", "Tangail", "Jamalpur" }));
        comboLibrarianDistrict.setFocusable(false);
        comboLibrarianDistrict.setVerifyInputWhenFocusTarget(false);

        comboLibrarianDivision.setEditable(true);
        comboLibrarianDivision.setFont(new java.awt.Font("SimSun", 0, 14)); // NOI18N
        comboLibrarianDivision.setForeground(new java.awt.Color(102, 102, 102));
        comboLibrarianDivision.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Division", "Dhaka", "Rajshahi", "Ctg", "khulna" }));

        jLabel106.setFont(new java.awt.Font("SimSun", 0, 15)); // NOI18N
        jLabel106.setForeground(new java.awt.Color(102, 102, 102));
        jLabel106.setText("Shift:");

        radioBtnShiftMorning.setBackground(new java.awt.Color(255, 255, 255));
        radioBtnShiftMorning.setFont(new java.awt.Font("SimSun", 0, 14)); // NOI18N
        radioBtnShiftMorning.setForeground(new java.awt.Color(51, 51, 51));
        radioBtnShiftMorning.setText("Morning");
        radioBtnShiftMorning.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        radioBtnShiftMorning.setBorderPainted(true);
        radioBtnShiftMorning.setIconTextGap(10);

        radioBtnShiftDay.setBackground(new java.awt.Color(255, 255, 255));
        radioBtnShiftDay.setFont(new java.awt.Font("SimSun", 0, 14)); // NOI18N
        radioBtnShiftDay.setForeground(new java.awt.Color(51, 51, 51));
        radioBtnShiftDay.setText("Day");
        radioBtnShiftDay.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        radioBtnShiftDay.setBorderPainted(true);
        radioBtnShiftDay.setIconTextGap(10);

        jLabel107.setFont(new java.awt.Font("SimSun", 0, 15)); // NOI18N
        jLabel107.setForeground(new java.awt.Color(102, 102, 102));
        jLabel107.setText("User Name:");

        txtLibrarianUserName.setFont(new java.awt.Font("SimSun", 0, 14)); // NOI18N
        txtLibrarianUserName.setForeground(new java.awt.Color(102, 102, 102));

        jLabel108.setFont(new java.awt.Font("SimSun", 0, 15)); // NOI18N
        jLabel108.setForeground(new java.awt.Color(102, 102, 102));
        jLabel108.setText("Password:");

        txtLibrarianPassword.setFont(new java.awt.Font("SimSun", 0, 14)); // NOI18N
        txtLibrarianPassword.setForeground(new java.awt.Color(102, 102, 102));

        jLabel110.setFont(new java.awt.Font("SimSun", 0, 15)); // NOI18N
        jLabel110.setForeground(new java.awt.Color(102, 102, 102));
        jLabel110.setText("Confirm Password:");

        txtLibrarianConfirmPassword.setFont(new java.awt.Font("SimSun", 0, 14)); // NOI18N
        txtLibrarianConfirmPassword.setForeground(new java.awt.Color(102, 102, 102));

        btnAddLibrarianRecord.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        btnAddLibrarianRecord.setForeground(new java.awt.Color(102, 102, 102));
        btnAddLibrarianRecord.setText("Add Record");
        btnAddLibrarianRecord.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 3));
        btnAddLibrarianRecord.setContentAreaFilled(false);
        btnAddLibrarianRecord.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddLibrarianRecord.setFocusPainted(false);
        btnAddLibrarianRecord.setFocusable(false);
        btnAddLibrarianRecord.setRequestFocusEnabled(false);
        btnAddLibrarianRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddLibrarianRecordActionPerformed(evt);
            }
        });

        jLabel111.setFont(new java.awt.Font("SimSun", 0, 15)); // NOI18N
        jLabel111.setForeground(new java.awt.Color(255, 0, 0));
        jLabel111.setText("must use up to 7 char");

        jLabel114.setFont(new java.awt.Font("SimSun", 0, 15)); // NOI18N
        jLabel114.setForeground(new java.awt.Color(255, 0, 0));
        jLabel114.setText("must use char \"a-z\"");

        javax.swing.GroupLayout jPanel33Layout = new javax.swing.GroupLayout(jPanel33);
        jPanel33.setLayout(jPanel33Layout);
        jPanel33Layout.setHorizontalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel33Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel107)
                    .addComponent(jLabel70)
                    .addComponent(jLabel76)
                    .addComponent(jLabel108)
                    .addComponent(jLabel110)
                    .addComponent(jLabel77, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel74, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel106))
                .addGap(41, 41, 41)
                .addGroup(jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel114, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel111, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtLibrarianCardNo)
                    .addComponent(txtLibrarianMobileNo)
                    .addComponent(txtLibrarianEmail)
                    .addComponent(txtLibrarianName)
                    .addComponent(txtLibrarianUserName)
                    .addComponent(txtLibrarianPassword)
                    .addGroup(jPanel33Layout.createSequentialGroup()
                        .addComponent(radioBtnShiftMorning, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioBtnShiftDay, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtLibrarianConfirmPassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel33Layout.createSequentialGroup()
                        .addGroup(jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel79)
                            .addComponent(jLabel71)
                            .addComponent(jLabel73)
                            .addComponent(jLabel72)
                            .addComponent(jLabel75)
                            .addComponent(jLabel78, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtLibrarianBlockOrvVillage)
                            .addComponent(txtLibrarianThana)
                            .addComponent(comboLibrarianDistrict, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboLibrarianDivision, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtLibrarianRoadNo, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLibrarianHouseNo, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblShowMsgInLibrarianAccountPan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddLibrarianRecord, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57))
        );
        jPanel33Layout.setVerticalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel33Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtLibrarianName)
                    .addComponent(jLabel76, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel70, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLibrarianCardNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel74, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLibrarianMobileNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel77, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLibrarianEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioBtnShiftDay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel106)
                    .addComponent(radioBtnShiftMorning, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel114, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLibrarianUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel107, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel111)
                .addGap(3, 3, 3)
                .addGroup(jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLibrarianPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel108, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLibrarianConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel110, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(165, 165, 165))
            .addGroup(jPanel33Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel78, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLibrarianHouseNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel71, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLibrarianRoadNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel73, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLibrarianBlockOrvVillage))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel79, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLibrarianThana))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel72, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboLibrarianDistrict, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel75, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboLibrarianDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblShowMsgInLibrarianAccountPan, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAddLibrarianRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(139, 139, 139))
        );

        jPanel34.setBackground(new java.awt.Color(255, 255, 255));
        jPanel34.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3));

        tblDisplayLibrarianAccount.setFont(new java.awt.Font("SimSun", 0, 14)); // NOI18N
        tblDisplayLibrarianAccount.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Librarian Name", "Librarian Card No", "Mobile No", "Email", "House No", "Road No", "Block/Village", "Thana", "District", "Division", "Shift"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDisplayLibrarianAccount.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblDisplayLibrarianAccount.setFillsViewportHeight(true);
        tblDisplayLibrarianAccount.setShowHorizontalLines(false);
        tblDisplayLibrarianAccount.setShowVerticalLines(false);
        tblDisplayLibrarianAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDisplayLibrarianAccountMouseClicked(evt);
            }
        });
        jScrollPane25.setViewportView(tblDisplayLibrarianAccount);

        javax.swing.GroupLayout jPanel34Layout = new javax.swing.GroupLayout(jPanel34);
        jPanel34.setLayout(jPanel34Layout);
        jPanel34Layout.setHorizontalGroup(
            jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel34Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane25)
                .addContainerGap())
        );
        jPanel34Layout.setVerticalGroup(
            jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel34Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane25, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel37.setBackground(new java.awt.Color(255, 255, 255));
        jPanel37.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3), "[ Delete Librarian Account ]", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SimSun", 0, 18), new java.awt.Color(51, 51, 51))); // NOI18N

        btnDeleteLibrarianAccount.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        btnDeleteLibrarianAccount.setForeground(new java.awt.Color(51, 51, 51));
        btnDeleteLibrarianAccount.setText("| Delete This Librarian ?");
        btnDeleteLibrarianAccount.setBorder(null);
        btnDeleteLibrarianAccount.setContentAreaFilled(false);
        btnDeleteLibrarianAccount.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDeleteLibrarianAccount.setFocusPainted(false);
        btnDeleteLibrarianAccount.setFocusable(false);
        btnDeleteLibrarianAccount.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnDeleteLibrarianAccount.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnDeleteLibrarianAccount.setRequestFocusEnabled(false);
        btnDeleteLibrarianAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteLibrarianAccountMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDeleteLibrarianAccountMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDeleteLibrarianAccountMouseExited(evt);
            }
        });
        btnDeleteLibrarianAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteLibrarianAccountActionPerformed(evt);
            }
        });

        txtLibrarianAccountSearchBar.setFont(new java.awt.Font("SimSun", 0, 14)); // NOI18N
        txtLibrarianAccountSearchBar.setForeground(new java.awt.Color(51, 51, 51));

        btnSearchLibrarianAccount.setFont(new java.awt.Font("SimSun", 0, 14)); // NOI18N
        btnSearchLibrarianAccount.setForeground(new java.awt.Color(102, 102, 102));
        btnSearchLibrarianAccount.setText("Search");
        btnSearchLibrarianAccount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 3));
        btnSearchLibrarianAccount.setContentAreaFilled(false);
        btnSearchLibrarianAccount.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearchLibrarianAccount.setFocusable(false);
        btnSearchLibrarianAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchLibrarianAccountActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));

        jLabel80.setFont(new java.awt.Font("SimSun", 0, 15)); // NOI18N
        jLabel80.setForeground(new java.awt.Color(102, 102, 102));
        jLabel80.setText("Librarian Name:");

        jLabel81.setFont(new java.awt.Font("SimSun", 0, 15)); // NOI18N
        jLabel81.setForeground(new java.awt.Color(102, 102, 102));
        jLabel81.setText("Librarian Code:");

        jLabel85.setFont(new java.awt.Font("SimSun", 0, 15)); // NOI18N
        jLabel85.setForeground(new java.awt.Color(102, 102, 102));
        jLabel85.setText("Mobile No:");

        jLabel95.setFont(new java.awt.Font("SimSun", 0, 15)); // NOI18N
        jLabel95.setForeground(new java.awt.Color(102, 102, 102));
        jLabel95.setText("Email:");

        lblShowLibrarianName.setFont(new java.awt.Font("SimSun", 0, 15)); // NOI18N
        lblShowLibrarianName.setForeground(new java.awt.Color(0, 153, 102));

        lblShowLibrarianCodeNo.setFont(new java.awt.Font("SimSun", 0, 15)); // NOI18N
        lblShowLibrarianCodeNo.setForeground(new java.awt.Color(0, 153, 102));

        lblShowLibrarianMobileNumber.setFont(new java.awt.Font("SimSun", 0, 15)); // NOI18N
        lblShowLibrarianMobileNumber.setForeground(new java.awt.Color(0, 153, 102));

        jLabel109.setFont(new java.awt.Font("SimSun", 0, 15)); // NOI18N
        jLabel109.setForeground(new java.awt.Color(102, 102, 102));
        jLabel109.setText("Address:");

        lblShowLibrarianEmail.setFont(new java.awt.Font("SimSun", 0, 15)); // NOI18N
        lblShowLibrarianEmail.setForeground(new java.awt.Color(0, 153, 102));

        lblShowLibrarianAddress.setFont(new java.awt.Font("SimSun", 0, 15)); // NOI18N
        lblShowLibrarianAddress.setForeground(new java.awt.Color(0, 153, 102));
        lblShowLibrarianAddress.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        lblShowDelLibrarianAccountPan.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        lblShowDelLibrarianAccountPan.setForeground(new java.awt.Color(255, 51, 51));
        lblShowDelLibrarianAccountPan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel81)
                    .addComponent(jLabel80)
                    .addComponent(jLabel85)
                    .addComponent(jLabel95))
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblShowLibrarianName, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel109, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblShowLibrarianCodeNo, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblShowLibrarianMobileNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblShowLibrarianEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lblShowLibrarianAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(lblShowDelLibrarianAccountPan, javax.swing.GroupLayout.PREFERRED_SIZE, 833, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel80, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblShowLibrarianName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel109, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel81, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblShowLibrarianCodeNo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel85, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblShowLibrarianMobileNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel95, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblShowLibrarianEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblShowLibrarianAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblShowDelLibrarianAccountPan, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
        );

        jLabel113.setFont(new java.awt.Font("SimSun", 0, 14)); // NOI18N
        jLabel113.setForeground(new java.awt.Color(51, 51, 51));
        jLabel113.setText(">> Search By Librarian Code NO: >>");

        btnClearDelLibrarianAccountPan.setFont(new java.awt.Font("SimSun", 0, 14)); // NOI18N
        btnClearDelLibrarianAccountPan.setForeground(new java.awt.Color(0, 153, 204));
        btnClearDelLibrarianAccountPan.setText("| CLEAR |");
        btnClearDelLibrarianAccountPan.setBorder(null);
        btnClearDelLibrarianAccountPan.setContentAreaFilled(false);
        btnClearDelLibrarianAccountPan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClearDelLibrarianAccountPan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnClearDelLibrarianAccountPanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnClearDelLibrarianAccountPanMouseExited(evt);
            }
        });
        btnClearDelLibrarianAccountPan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearDelLibrarianAccountPanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel37Layout = new javax.swing.GroupLayout(jPanel37);
        jPanel37.setLayout(jPanel37Layout);
        jPanel37Layout.setHorizontalGroup(
            jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel37Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel37Layout.createSequentialGroup()
                        .addComponent(jLabel113, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLibrarianAccountSearchBar, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSearchLibrarianAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(162, 162, 162)
                        .addComponent(btnClearDelLibrarianAccountPan))
                    .addGroup(jPanel37Layout.createSequentialGroup()
                        .addComponent(btnDeleteLibrarianAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel37Layout.setVerticalGroup(
            jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel37Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtLibrarianAccountSearchBar)
                    .addComponent(jLabel113, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel37Layout.createSequentialGroup()
                        .addGroup(jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSearchLibrarianAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnClearDelLibrarianAccountPan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(btnDeleteLibrarianAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel4.setFont(new java.awt.Font("SimSun", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("> Search Librarian Account: ");

        jLabel13.setFont(new java.awt.Font("SimSun", 0, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("* Search librarian account from database...");

        jLabel14.setFont(new java.awt.Font("SimSun", 0, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("* If you want delete librarian record than,");

        jLabel112.setFont(new java.awt.Font("SimSun", 0, 16)); // NOI18N
        jLabel112.setForeground(new java.awt.Color(255, 0, 51));
        jLabel112.setText("-> Click ( Delete Selected Librarian ) button.");

        jLabel82.setFont(new java.awt.Font("SimSun", 0, 15)); // NOI18N
        jLabel82.setForeground(new java.awt.Color(0, 153, 204));
        jLabel82.setText("| A room without BOOKS is like a body without a soul.     ......Marcus Tullius Cicero");

        javax.swing.GroupLayout subPanCreateAdminAccountLayout = new javax.swing.GroupLayout(subPanCreateAdminAccount);
        subPanCreateAdminAccount.setLayout(subPanCreateAdminAccountLayout);
        subPanCreateAdminAccountLayout.setHorizontalGroup(
            subPanCreateAdminAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subPanCreateAdminAccountLayout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addGroup(subPanCreateAdminAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(subPanCreateAdminAccountLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(subPanCreateAdminAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13)))
                    .addGroup(subPanCreateAdminAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel84)
                        .addGroup(subPanCreateAdminAccountLayout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jLabel112, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jPanel37, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel82))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        subPanCreateAdminAccountLayout.setVerticalGroup(
            subPanCreateAdminAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, subPanCreateAdminAccountLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel84)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel82)
                .addGap(71, 71, 71)
                .addComponent(jPanel33, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel112)
                .addGap(49, 49, 49)
                .addComponent(jPanel37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(121, Short.MAX_VALUE))
        );

        scPanCreateAdminAccount.setViewportView(subPanCreateAdminAccount);

        javax.swing.GroupLayout jpanCreateAdminAccountLayout = new javax.swing.GroupLayout(jpanCreateAdminAccount);
        jpanCreateAdminAccount.setLayout(jpanCreateAdminAccountLayout);
        jpanCreateAdminAccountLayout.setHorizontalGroup(
            jpanCreateAdminAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scPanCreateAdminAccount, javax.swing.GroupLayout.DEFAULT_SIZE, 773, Short.MAX_VALUE)
        );
        jpanCreateAdminAccountLayout.setVerticalGroup(
            jpanCreateAdminAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scPanCreateAdminAccount, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 793, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jpanCreateAdminAccount, javax.swing.GroupLayout.DEFAULT_SIZE, 773, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 541, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jpanCreateAdminAccount, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddLibrarianRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddLibrarianRecordActionPerformed
        // TODO add your handling code here:

        librarianAccount = new LibrarianAccount();
        librarianService = new LibrarianService();

        librarianAccount.setName(txtLibrarianName.getText());
        librarianAccount.setCodeNumber(Integer.parseInt(txtLibrarianCardNo.getText()));
        librarianAccount.setContactInfo(txtLibrarianMobileNo.getText(), txtLibrarianEmail.getText());
        librarianAccount.setAddressInfo(
            txtLibrarianHouseNo.getText(),
            txtLibrarianRoadNo.getText(),
            txtLibrarianBlockOrvVillage.getText(),
            txtLibrarianThana.getText(),
            comboLibrarianDistrict.getSelectedItem().toString(),
            comboLibrarianDivision.getSelectedItem().toString()
        );
        if (radioBtnShiftMorning.isSelected()) {
            librarianAccount.setShift("Morning");
        } else if (radioBtnShiftDay.isSelected()) {
            librarianAccount.setShift("Day");
        }
        librarianAccount.setUserName(txtLibrarianUserName.getText());

        if ((txtLibrarianPassword.getText()).equals(txtLibrarianConfirmPassword.getText())) {
            librarianAccount.setPassword(txtLibrarianPassword.getText());

            librarianService.saveLibrarianInformation(librarianAccount);
            lblShowMsgInLibrarianAccountPan.setText("Record add successful");

            resetLibrarianInformation();
        } else {
            txtLibrarianConfirmPassword.setForeground(Color.red);
            lblShowMsgInLibrarianAccountPan.setText("*/ Please CONFIRM your password /*");
        }

        clearTableForLibrarianInformation();
    }//GEN-LAST:event_btnAddLibrarianRecordActionPerformed

    private void tblDisplayLibrarianAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDisplayLibrarianAccountMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblDisplayLibrarianAccountMouseClicked

    private void btnDeleteLibrarianAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteLibrarianAccountMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteLibrarianAccountMouseClicked

    private void btnDeleteLibrarianAccountMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteLibrarianAccountMouseEntered
        // TODO add your handling code here:
        btnDeleteLibrarianAccount.setForeground(new Color(255, 0, 51));
    }//GEN-LAST:event_btnDeleteLibrarianAccountMouseEntered

    private void btnDeleteLibrarianAccountMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteLibrarianAccountMouseExited
        // TODO add your handling code here:
        btnDeleteLibrarianAccount.setForeground(new Color(51, 51, 51));
    }//GEN-LAST:event_btnDeleteLibrarianAccountMouseExited

    private void btnDeleteLibrarianAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteLibrarianAccountActionPerformed
        // TODO add your handling code here:
        librarianService = new LibrarianService();
        if (librarianID > 0) {
            librarianService.deleteLibrarianInformation(librarianID);
            clearLibrarianSearchOption();
            clearTableForLibrarianInformation();
            lblShowDelLibrarianAccountPan.setText("Delete This Librarian Information successful");
        }
        librarianID = 0;
    }//GEN-LAST:event_btnDeleteLibrarianAccountActionPerformed

    private void btnSearchLibrarianAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchLibrarianAccountActionPerformed
        // TODO add your handling code here:

        librarianService = new LibrarianService();

        librarianAccount = librarianService.searchLibrarianAccountByCodeNo(Integer.parseInt(txtLibrarianAccountSearchBar.getText()));
        if (librarianAccount.getName() != null) {
            librarianID = librarianAccount.getId();
            lblShowLibrarianName.setText(librarianAccount.getName());
            lblShowLibrarianCodeNo.setText(String.valueOf(librarianAccount.getCodeNumber()));
            lblShowLibrarianMobileNumber.setText(librarianAccount.getContactInfo().getMobileNumber());
            lblShowLibrarianEmail.setText(librarianAccount.getContactInfo().getEmail());
            lblShowLibrarianAddress.setText(
                librarianAccount.getAddressInfo().getHouseNo()
                + ", " + librarianAccount.getAddressInfo().getRoadNo()
                + ", " + librarianAccount.getAddressInfo().getBlockOrVillage()
                + ", " + librarianAccount.getAddressInfo().getThana()
                + ", " + librarianAccount.getAddressInfo().getDistrict()
                + ", " + librarianAccount.getAddressInfo().getDivision()
            );
            lblShowDelLibrarianAccountPan.setText(null);
        } else {
            lblShowDelLibrarianAccountPan.setText("This code number not available in databese");
        }
    }//GEN-LAST:event_btnSearchLibrarianAccountActionPerformed

    private void btnClearDelLibrarianAccountPanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearDelLibrarianAccountPanMouseEntered
        // TODO add your handling code here:
        btnClearDelLibrarianAccountPan.setForeground(new Color(255, 102, 0));
    }//GEN-LAST:event_btnClearDelLibrarianAccountPanMouseEntered

    private void btnClearDelLibrarianAccountPanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearDelLibrarianAccountPanMouseExited
        // TODO add your handling code here:
        btnClearDelLibrarianAccountPan.setForeground(new Color(0, 153, 204));
    }//GEN-LAST:event_btnClearDelLibrarianAccountPanMouseExited

    private void btnClearDelLibrarianAccountPanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearDelLibrarianAccountPanActionPerformed
        // TODO add your handling code here:
        clearLibrarianSearchOption();
        clearTableForLibrarianInformation();
    }//GEN-LAST:event_btnClearDelLibrarianAccountPanActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
         this.setExtendedState(this.getExtendedState() | JFrame.MAXIMIZED_BOTH);
    }//GEN-LAST:event_formWindowOpened

    
    private void displayLibrarianInformationWithInTable() {

        librarianService = new LibrarianService();

        List<LibrarianAccount> getLibrarian = librarianService.getLibrarianInformationList();
        DefaultTableModel model = (DefaultTableModel) tblDisplayLibrarianAccount.getModel();
        Object[] row = new Object[12];

        for (int i = 0; i < getLibrarian.size(); i++) {

            row[0] = getLibrarian.get(i).getId();
            row[1] = getLibrarian.get(i).getName();
            row[2] = getLibrarian.get(i).getCodeNumber();
            row[3] = getLibrarian.get(i).getContactInfo().getMobileNumber();
            row[4] = getLibrarian.get(i).getContactInfo().getEmail();
            row[5] = getLibrarian.get(i).getAddressInfo().getHouseNo();
            row[6] = getLibrarian.get(i).getAddressInfo().getRoadNo();
            row[7] = getLibrarian.get(i).getAddressInfo().getBlockOrVillage();
            row[8] = getLibrarian.get(i).getAddressInfo().getThana();
            row[9] = getLibrarian.get(i).getAddressInfo().getDistrict();
            row[10] = getLibrarian.get(i).getAddressInfo().getDivision();
            row[11] = getLibrarian.get(i).getShift();

            model.addRow(row);
        }
    }

    private void clearTableForLibrarianInformation() {

        DefaultTableModel model = (DefaultTableModel) tblDisplayLibrarianAccount.getModel();
        model.setRowCount(0);

        displayLibrarianInformationWithInTable();

    }
    
    
    private void resetLibrarianInformation() {

        txtLibrarianName.setText(null);
        txtLibrarianCardNo.setText(null);
        txtLibrarianMobileNo.setText(null);
        txtLibrarianEmail.setText(null);
        txtLibrarianHouseNo.setText(null);
        txtLibrarianRoadNo.setText(null);
        txtLibrarianBlockOrvVillage.setText(null);
        txtLibrarianThana.setText(null);
        txtLibrarianUserName.setText(null);
        txtLibrarianPassword.setText(null);
        txtLibrarianConfirmPassword.setText(null);
        comboLibrarianDistrict.setSelectedIndex(0);
        comboLibrarianDivision.setSelectedIndex(0);

    }


    private void clearLibrarianSearchOption() {

        txtLibrarianAccountSearchBar.setText(null);
        lblShowLibrarianName.setText(null);
        lblShowLibrarianCodeNo.setText(null);
        lblShowLibrarianMobileNumber.setText(null);
        lblShowLibrarianEmail.setText(null);
        lblShowLibrarianAddress.setText(null);
        lblShowDelLibrarianAccountPan.setText(null);
        librarianID = 0;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateLibrarianAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateLibrarianAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateLibrarianAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateLibrarianAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateLibrarianAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddLibrarianRecord;
    private javax.swing.JButton btnClearDelLibrarianAccountPan;
    private javax.swing.JButton btnDeleteLibrarianAccount;
    private javax.swing.JButton btnSearchLibrarianAccount;
    private javax.swing.JComboBox<String> comboLibrarianDistrict;
    private javax.swing.JComboBox<String> comboLibrarianDivision;
    private javax.swing.JLabel jLabel106;
    private javax.swing.JLabel jLabel107;
    private javax.swing.JLabel jLabel108;
    private javax.swing.JLabel jLabel109;
    private javax.swing.JLabel jLabel110;
    private javax.swing.JLabel jLabel111;
    private javax.swing.JLabel jLabel112;
    private javax.swing.JLabel jLabel113;
    private javax.swing.JLabel jLabel114;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane25;
    private javax.swing.JPanel jpanCreateAdminAccount;
    private javax.swing.JLabel lblShowDelLibrarianAccountPan;
    private javax.swing.JLabel lblShowLibrarianAddress;
    private javax.swing.JLabel lblShowLibrarianCodeNo;
    private javax.swing.JLabel lblShowLibrarianEmail;
    private javax.swing.JLabel lblShowLibrarianMobileNumber;
    private javax.swing.JLabel lblShowLibrarianName;
    private javax.swing.JLabel lblShowMsgInLibrarianAccountPan;
    private javax.swing.JScrollBar librarianScrolBar;
    private javax.swing.JRadioButton radioBtnShiftDay;
    private javax.swing.JRadioButton radioBtnShiftMorning;
    private javax.swing.JScrollPane scPanCreateAdminAccount;
    private javax.swing.JPanel subPanCreateAdminAccount;
    private javax.swing.JTable tblDisplayLibrarianAccount;
    private javax.swing.JTextField txtLibrarianAccountSearchBar;
    private javax.swing.JTextField txtLibrarianBlockOrvVillage;
    private javax.swing.JTextField txtLibrarianCardNo;
    private javax.swing.JTextField txtLibrarianConfirmPassword;
    private javax.swing.JTextField txtLibrarianEmail;
    private javax.swing.JTextField txtLibrarianHouseNo;
    private javax.swing.JTextField txtLibrarianMobileNo;
    private javax.swing.JTextField txtLibrarianName;
    private javax.swing.JTextField txtLibrarianPassword;
    private javax.swing.JTextField txtLibrarianRoadNo;
    private javax.swing.JTextField txtLibrarianThana;
    private javax.swing.JTextField txtLibrarianUserName;
    // End of variables declaration//GEN-END:variables
}
